kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.config.storage.resourceName }}-secret
type: Opaque
data:
  azurestorageaccountname: "{{ .Values.config.storage.azureFile.azureStorageAccountName | b64enc }}"
  azurestorageaccountkey: "{{ .Values.config.storage.azureFile.azureStorageAccountKey | b64enc }}"
